//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeShare.RecipeSearchServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecipeSearchServiceReference.IRecipeSearchService")]
    public interface IRecipeSearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeSearchService/GetRecipeNames", ReplyAction="http://tempuri.org/IRecipeSearchService/GetRecipeNamesResponse")]
        string[] GetRecipeNames(string prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeSearchService/GetRecipeNames", ReplyAction="http://tempuri.org/IRecipeSearchService/GetRecipeNamesResponse")]
        System.Threading.Tasks.Task<string[]> GetRecipeNamesAsync(string prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeSearchService/GetIngredients", ReplyAction="http://tempuri.org/IRecipeSearchService/GetIngredientsResponse")]
        string[] GetIngredients(string prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeSearchService/GetIngredients", ReplyAction="http://tempuri.org/IRecipeSearchService/GetIngredientsResponse")]
        System.Threading.Tasks.Task<string[]> GetIngredientsAsync(string prefix);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecipeSearchServiceChannel : RecipeShare.RecipeSearchServiceReference.IRecipeSearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecipeSearchServiceClient : System.ServiceModel.ClientBase<RecipeShare.RecipeSearchServiceReference.IRecipeSearchService>, RecipeShare.RecipeSearchServiceReference.IRecipeSearchService {
        
        public RecipeSearchServiceClient() {
        }
        
        public RecipeSearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecipeSearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeSearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeSearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetRecipeNames(string prefix) {
            return base.Channel.GetRecipeNames(prefix);
        }
        
        public System.Threading.Tasks.Task<string[]> GetRecipeNamesAsync(string prefix) {
            return base.Channel.GetRecipeNamesAsync(prefix);
        }
        
        public string[] GetIngredients(string prefix) {
            return base.Channel.GetIngredients(prefix);
        }
        
        public System.Threading.Tasks.Task<string[]> GetIngredientsAsync(string prefix) {
            return base.Channel.GetIngredientsAsync(prefix);
        }
    }
}
