<?xml version="1.0" encoding="utf-8"?><Database Name="Recipes" Class="RecipeSearchDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=C:\Code\Recipe\RecipeShare\RecipeShare\App_Data\Recipes.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RecipeContext" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Image" Member="Images">
    <Type Name="Image">
      <Column Name="ImageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecipeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="URI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Recipe_Image" Member="Recipe" ThisKey="RecipeID" OtherKey="RecipeID" Type="Recipe" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ingredient" Member="Ingredients">
    <Type Name="Ingredient">
      <Column Name="IngredientID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecipeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MeasureID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IngredientNameID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="IngredientName_Ingredient" Member="IngredientName" ThisKey="IngredientNameID" OtherKey="IngredientNameID" Type="IngredientName" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Measure_Ingredient" Member="Measure" ThisKey="MeasureID" OtherKey="MeasureID" Type="Measure" IsForeignKey="true" />
      <Association Name="Recipe_Ingredient" Member="Recipe" ThisKey="RecipeID" OtherKey="RecipeID" Type="Recipe" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngredientName" Member="IngredientNames">
    <Type Name="IngredientName">
      <Column Name="IngredientNameID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="IngredientName_Ingredient" Member="Ingredients" ThisKey="IngredientNameID" OtherKey="IngredientNameID" Type="Ingredient" />
    </Type>
  </Table>
  <Table Name="dbo.Measure" Member="Measures">
    <Type Name="Measure">
      <Column Name="MeasureID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Association Name="Measure_Ingredient" Member="Ingredients" ThisKey="MeasureID" OtherKey="MeasureID" Type="Ingredient" />
    </Type>
  </Table>
  <Table Name="dbo.Recipe" Member="Recipes">
    <Type Name="Recipe">
      <Column Name="RecipeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rating" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Votes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Instructions" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Recipe_RecipeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Recipe_Image" Member="Images" ThisKey="RecipeID" OtherKey="RecipeID" Type="Image" />
      <Association Name="Recipe_Ingredient" Member="Ingredients" ThisKey="RecipeID" OtherKey="RecipeID" Type="Ingredient" />
      <Association Name="Recipe_Recipe" Member="Recipes" ThisKey="RecipeID" OtherKey="Recipe_RecipeID" Type="Recipe" />
      <Association Name="Recipe_Review" Member="Reviews" ThisKey="RecipeID" OtherKey="RecipeID" Type="Review" />
      <Association Name="Recipe_Recipe" Member="Recipe1" ThisKey="Recipe_RecipeID" OtherKey="RecipeID" Type="Recipe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Review" Member="Reviews">
    <Type Name="Review">
      <Column Name="ReviewID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecipeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Entry" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Recipe_Review" Member="Recipe" ThisKey="RecipeID" OtherKey="RecipeID" Type="Recipe" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>